# Generated by Django 3.2.4 on 2021-07-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=12)),
                ('Last_name', models.CharField(max_length=12)),
                ('age', models.PositiveSmallIntegerField()),
                ('Date_Of_Birth', models.DateField()),
                ('Subject', models.CharField(max_length=20)),
            ],
        ),
    ]
