# Generated by Django 3.2.4 on 2021-07-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=20)),
                ('Course_Trainer', models.CharField(max_length=12)),
                ('Course_Description', models.CharField(max_length=35)),
                ('Course_Duration', models.IntegerField()),
            ],
        ),
    ]
